BEGIN TRY

BEGIN TRAN;

-- DropForeignKey
ALTER TABLE [dbo].[Rental] DROP CONSTRAINT [Rental_clientId_fkey];

-- AddForeignKey
ALTER TABLE [dbo].[Rental] ADD CONSTRAINT [Rental_clientId_fkey] FOREIGN KEY ([clientId]) REFERENCES [dbo].[User]([username]) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
