insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Subaru', 'Legacy', 'Automatic', 'Fuel-Oil', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'GMC', 'Envoy', 'Automatic', 'Diesel', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Ford', 'Thunderbird', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Acura', 'TL', 'Manual', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Chevrolet', 'Silverado', 'Manual', 'Diesel', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Ford', 'Mustang', 'Automatic', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Oldsmobile', 'Silhouette', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Oldsmobile', 'Regency', 'Manual', 'Hybrid', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Honda', 'Prelude', 'Automatic', 'Gas', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Maybach', 'Landaulet', 'Manual', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Volkswagen', 'Golf', 'Automatic', 'Hybrid', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Nissan', 'Xterra', 'Manual', 'Gas', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Eagle', 'Talon', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Nissan', 'Sentra', 'Automatic', 'Fuel-Oil', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Pontiac', 'Sunbird', 'Automatic', 'Hybrid', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Chevrolet', 'Sportvan G20', 'Automatic', 'Electric', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Mitsubishi', 'GTO', 'Manual', 'Electric', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Audi', 'A6', 'Manual', 'Gas', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Mazda', 'B-Series', 'Automatic', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Kia', 'Rio', 'Manual', 'Fuel-Oil', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Plymouth', 'Colt', 'Manual', 'Fuel-Oil', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Nissan', '350Z Roadster', 'Manual', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Ford', 'Windstar', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Pontiac', 'Vibe', 'Automatic', 'Hybrid', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Cadillac', 'CTS', 'Manual', 'Gas', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'GMC', 'Canyon', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Honda', 'Fit', 'Manual', 'Electric', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Mercury', 'Mystique', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Cadillac', 'CTS', 'Automatic', 'Gas', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Mazda', 'CX-9', 'Manual', 'Diesel', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Nissan', 'Murano', 'Automatic', 'Diesel', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Lincoln', 'Mark VIII', 'Manual', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Nissan', '300ZX', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Dodge', 'Ram Van 1500', 'Automatic', 'Gas', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Porsche', 'Cayenne', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Buick', 'Terraza', 'Manual', 'Gas', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Dodge', 'Viper', 'Automatic', 'Fuel-Oil', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Mazda', 'MX-6', 'Manual', 'Gas', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Ford', 'Explorer Sport Trac', 'Manual', 'Fuel-Oil', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Honda', 'CR-X', 'Automatic', 'Hybrid', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Dodge', 'Viper', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Mitsubishi', 'Lancer', 'Manual', 'Hybrid', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Volvo', 'S60', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Audi', 'A5', 'Automatic', 'Hybrid', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Kia', 'Sedona', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Plymouth', 'Colt', 'Automatic', 'Hybrid', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Isuzu', 'Trooper', 'Manual', 'Fuel-Oil', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Pontiac', 'Aztek', 'Manual', 'Gas', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Volvo', 'C70', 'Manual', 'Hybrid', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Ford', 'Excursion', 'Manual', 'Hybrid', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Chevrolet', 'Suburban 1500', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Buick', 'Lucerne', 'Automatic', 'Gas', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Ford', 'Ranger', 'Automatic', 'Diesel', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Mazda', 'B-Series', 'Automatic', 'Electric', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Mercury', 'Lynx', 'Manual', 'Gas', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Pontiac', 'Gemini', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Isuzu', 'i-350', 'Automatic', 'Hybrid', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Chevrolet', '3500', 'Automatic', 'Hybrid', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Hyundai', 'Accent', 'Automatic', 'Hybrid', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Honda', 'Element', 'Manual', 'Gas', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Mercury', 'Milan', 'Manual', 'Diesel', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Chevrolet', 'Corvette', 'Automatic', 'Gas', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Hyundai', 'Accent', 'Manual', 'Fuel-Oil', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Dodge', 'Ram Wagon B150', 'Manual', 'Hybrid', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Buick', 'Century', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Dodge', 'Ram 2500 Club', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Mercedes-Benz', 'S-Class', 'Automatic', 'Gas', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Audi', 'TT', 'Manual', 'Diesel', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Chevrolet', 'Beretta', 'Manual', 'Diesel', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Lexus', 'IS-F', 'Automatic', 'Gas', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Nissan', '240SX', 'Automatic', 'Diesel', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Isuzu', 'i-290', 'Automatic', 'Fuel-Oil', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Hyundai', 'Elantra', 'Manual', 'Hybrid', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Honda', 'Civic', 'Manual', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Jeep', 'Wrangler', 'Manual', 'Diesel', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Cadillac', 'CTS-V', 'Manual', 'Diesel', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Mazda', 'Millenia', 'Automatic', 'Diesel', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Pontiac', 'Parisienne', 'Manual', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Acura', 'NSX', 'Automatic', 'Gas', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Volkswagen', 'Jetta', 'Automatic', 'Fuel-Oil', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Mercedes-Benz', 'SL-Class', 'Automatic', 'Hybrid', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Toyota', 'Camry Hybrid', 'Automatic', 'Diesel', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Audi', 'A6', 'Manual', 'Gas', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Porsche', '911', 'Manual', 'Gas', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Mazda', 'RX-7', 'Automatic', 'Diesel', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Dodge', 'Durango', 'Manual', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Mitsubishi', 'Mirage', 'Automatic', 'Fuel-Oil', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Ford', 'Taurus', 'Automatic', 'Fuel-Oil', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Mercedes-Benz', 'E-Class', 'Automatic', 'Hybrid', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Buick', 'Century', 'Automatic', 'Diesel', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Chevrolet', 'Prizm', 'Automatic', 'Hybrid', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Isuzu', 'i-350', 'Manual', 'Diesel', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Buick', 'LeSabre', 'Automatic', 'Diesel', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Mercedes-Benz', 'E-Class', 'Manual', 'Diesel', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Lexus', 'ES', 'Automatic', 'Hybrid', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Dodge', 'Caravan', 'Automatic', 'Gas', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Ferrari', '612 Scaglietti', 'Manual', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'BMW', 'X3', 'Automatic', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Nissan', 'Quest', 'Manual', 'Gas', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Audi', 'A6', 'Manual', 'Fuel-Oil', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'GMC', 'Sierra', 'Automatic', 'Fuel-Oil', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Dodge', 'Charger', 'Automatic', 'Gas', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Mazda', 'MPV', 'Automatic', 'Diesel', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Subaru', 'Outback', 'Automatic', 'Electric', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Nissan', 'Maxima', 'Manual', 'Hybrid', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Lexus', 'GS', 'Automatic', 'Gas', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'BMW', '6 Series', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Buick', 'Lucerne', 'Automatic', 'Diesel', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Dodge', 'Dakota', 'Manual', 'Diesel', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Lincoln', 'Town Car', 'Automatic', 'Hybrid', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Land Rover', 'Discovery', 'Automatic', 'Fuel-Oil', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Mercedes-Benz', 'E-Class', 'Manual', 'Hybrid', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Cadillac', 'CTS', 'Automatic', 'Hybrid', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Mercedes-Benz', 'S-Class', 'Automatic', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Hyundai', 'Excel', 'Manual', 'Diesel', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Chevrolet', 'Equinox', 'Manual', 'Gas', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Chevrolet', '1500', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Lotus', 'Exige', 'Manual', 'Hybrid', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Suzuki', 'Swift', 'Automatic', 'Hybrid', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Cadillac', 'DeVille', 'Automatic', 'Hybrid', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Volkswagen', 'Touareg', 'Automatic', 'Fuel-Oil', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Oldsmobile', 'Achieva', 'Manual', 'Gas', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Audi', '100', 'Manual', 'Fuel-Oil', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Pontiac', 'Gemini', 'Manual', 'Hybrid', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Scion', 'xB', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Kia', 'Optima', 'Automatic', 'Gas', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Ford', 'Expedition', 'Manual', 'Fuel-Oil', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Buick', 'Century', 'Automatic', 'Diesel', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Chrysler', 'Voyager', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Chevrolet', 'Express 2500', 'Automatic', 'Fuel-Oil', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Bentley', 'Azure', 'Manual', 'Electric', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Hyundai', 'Entourage', 'Manual', 'Hybrid', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Mercedes-Benz', 'E-Class', 'Automatic', 'Diesel', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Dodge', 'Intrepid', 'Manual', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Mitsubishi', 'Galant', 'Automatic', 'Fuel-Oil', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Kia', 'Sportage', 'Manual', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Toyota', 'Avalon', 'Automatic', 'Fuel-Oil', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Chevrolet', 'Avalanche 1500', 'Manual', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Chevrolet', 'Impala', 'Automatic', 'Hybrid', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Volkswagen', 'Passat', 'Automatic', 'Hybrid', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Dodge', 'Stealth', 'Manual', 'Fuel-Oil', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'GMC', 'Jimmy', 'Manual', 'Fuel-Oil', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Mercury', 'Mountaineer', 'Automatic', 'Gas', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Lincoln', 'Navigator L', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Suzuki', 'XL-7', 'Automatic', 'Gas', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Subaru', 'Forester', 'Manual', 'Gas', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Saturn', 'L-Series', 'Manual', 'Gas', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Scion', 'xB', 'Automatic', 'Hybrid', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Chrysler', 'Town & Country', 'Manual', 'Diesel', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Oldsmobile', 'Cutlass', 'Manual', 'Hybrid', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Nissan', 'Cube', 'Manual', 'Hybrid', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'GMC', 'Savana 2500', 'Automatic', 'Gas', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Volvo', 'V70', 'Manual', 'Diesel', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Mercedes-Benz', 'C-Class', 'Automatic', 'Hybrid', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Mitsubishi', 'Eclipse', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'BMW', 'Z8', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Infiniti', 'Q', 'Manual', 'Gas', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Pontiac', 'GTO', 'Manual', 'Hybrid', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Oldsmobile', 'Aurora', 'Manual', 'Fuel-Oil', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Pontiac', 'Daewoo Kalos', 'Manual', 'Gas', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'GMC', 'Suburban 2500', 'Manual', 'Gas', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Porsche', 'Boxster', 'Manual', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Dodge', 'Neon', 'Manual', 'Hybrid', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Chevrolet', 'Corvette', 'Manual', 'Gas', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Buick', 'LeSabre', 'Manual', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Infiniti', 'G25', 'Manual', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Chevrolet', 'Aveo', 'Automatic', 'Diesel', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Mazda', 'B-Series Plus', 'Manual', 'Fuel-Oil', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Honda', 'Odyssey', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Subaru', 'Justy', 'Manual', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Pontiac', 'Aztek', 'Automatic', 'Electric', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Ford', 'Focus', 'Manual', 'Diesel', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Saab', '9-3', 'Manual', 'Hybrid', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Volkswagen', 'Touareg', 'Manual', 'Gas', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Lexus', 'IS-F', 'Automatic', 'Hybrid', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Kia', 'Carens', 'Automatic', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Ford', 'F450', 'Automatic', 'Gas', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Pontiac', 'GTO', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Chrysler', 'Aspen', 'Manual', 'Electric', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'BMW', '5 Series', 'Automatic', 'Gas', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'GMC', '3500 Club Coupe', 'Automatic', 'Gas', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Ford', 'Explorer', 'Manual', 'Gas', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Lincoln', 'MKS', 'Manual', 'Electric', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Ford', 'Econoline E150', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Ford', 'F-Series', 'Automatic', 'Diesel', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Mazda', 'RX-7', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Toyota', '4Runner', 'Manual', 'Hybrid', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Isuzu', 'VehiCROSS', 'Manual', 'Electric', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Dodge', 'Ram 2500', 'Automatic', 'Fuel-Oil', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Nissan', 'Leaf', 'Automatic', 'Hybrid', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Ford', 'Mustang', 'Automatic', 'Hybrid', 'Coupe');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Isuzu', 'i-370', 'Manual', 'Hybrid', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Budget', 'Lexus', 'GS', 'Automatic', 'Diesel', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Chevrolet', '1500', 'Automatic', 'Diesel', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Audi', 'A6', 'Automatic', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Premium', 'Acura', 'MDX', 'Automatic', 'Electric', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Standart', 'Pontiac', 'Parisienne', 'Automatic', 'Diesel', 'Hatchback');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Ford', 'E350', 'Automatic', 'Hybrid', 'Sedan');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'Volkswagen', 'rio', 'Manual', 'Diesel', 'SUV');
insert into Vehicles (class, make, model, transmission, engineType, bodyType) values ('Luxury', 'GMC', '1500 Club Coupe', 'Manual', 'Electric', 'SUV');
