insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (1, 'Budget', 'Subaru', 'Legacy', 'Automatic', 'Fuel-Oil', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (2, 'Luxury', 'GMC', 'Envoy', 'Automatic', 'Diesel', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (3, 'Standart', 'Ford', 'Thunderbird', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (4, 'Luxury', 'Acura', 'TL', 'Manual', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (5, 'Standart', 'Chevrolet', 'Silverado', 'Manual', 'Diesel', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (6, 'Luxury', 'Ford', 'Mustang', 'Automatic', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (7, 'Luxury', 'Oldsmobile', 'Silhouette', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (8, 'Budget', 'Oldsmobile', 'Regency', 'Manual', 'Hybrid', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (9, 'Standart', 'Honda', 'Prelude', 'Automatic', 'Gas', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (10, 'Luxury', 'Maybach', 'Landaulet', 'Manual', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (11, 'Luxury', 'Volkswagen', 'Golf', 'Automatic', 'Hybrid', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (12, 'Luxury', 'Nissan', 'Xterra', 'Manual', 'Gas', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (13, 'Luxury', 'Eagle', 'Talon', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (14, 'Budget', 'Nissan', 'Sentra', 'Automatic', 'Fuel-Oil', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (15, 'Luxury', 'Pontiac', 'Sunbird', 'Automatic', 'Hybrid', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (16, 'Premium', 'Chevrolet', 'Sportvan G20', 'Automatic', 'Electric', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (17, 'Standart', 'Mitsubishi', 'GTO', 'Manual', 'Electric', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (18, 'Luxury', 'Audi', 'A6', 'Manual', 'Gas', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (19, 'Standart', 'Mazda', 'B-Series', 'Automatic', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (20, 'Standart', 'Kia', 'Rio', 'Manual', 'Fuel-Oil', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (21, 'Luxury', 'Plymouth', 'Colt', 'Manual', 'Fuel-Oil', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (22, 'Budget', 'Nissan', '350Z Roadster', 'Manual', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (23, 'Standart', 'Ford', 'Windstar', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (24, 'Standart', 'Pontiac', 'Vibe', 'Automatic', 'Hybrid', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (25, 'Standart', 'Cadillac', 'CTS', 'Manual', 'Gas', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (26, 'Premium', 'GMC', 'Canyon', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (27, 'Luxury', 'Honda', 'Fit', 'Manual', 'Electric', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (28, 'Standart', 'Mercury', 'Mystique', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (29, 'Luxury', 'Cadillac', 'CTS', 'Automatic', 'Gas', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (30, 'Budget', 'Mazda', 'CX-9', 'Manual', 'Diesel', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (31, 'Standart', 'Nissan', 'Murano', 'Automatic', 'Diesel', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (32, 'Luxury', 'Lincoln', 'Mark VIII', 'Manual', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (33, 'Budget', 'Nissan', '300ZX', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (34, 'Luxury', 'Dodge', 'Ram Van 1500', 'Automatic', 'Gas', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (35, 'Budget', 'Porsche', 'Cayenne', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (36, 'Budget', 'Buick', 'Terraza', 'Manual', 'Gas', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (37, 'Budget', 'Dodge', 'Viper', 'Automatic', 'Fuel-Oil', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (38, 'Budget', 'Mazda', 'MX-6', 'Manual', 'Gas', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (39, 'Standart', 'Ford', 'Explorer Sport Trac', 'Manual', 'Fuel-Oil', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (40, 'Standart', 'Honda', 'CR-X', 'Automatic', 'Hybrid', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (41, 'Budget', 'Dodge', 'Viper', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (42, 'Budget', 'Mitsubishi', 'Lancer', 'Manual', 'Hybrid', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (43, 'Premium', 'Volvo', 'S60', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (44, 'Premium', 'Audi', 'A5', 'Automatic', 'Hybrid', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (45, 'Premium', 'Kia', 'Sedona', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (46, 'Budget', 'Plymouth', 'Colt', 'Automatic', 'Hybrid', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (47, 'Premium', 'Isuzu', 'Trooper', 'Manual', 'Fuel-Oil', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (48, 'Premium', 'Pontiac', 'Aztek', 'Manual', 'Gas', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (49, 'Budget', 'Volvo', 'C70', 'Manual', 'Hybrid', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (50, 'Budget', 'Ford', 'Excursion', 'Manual', 'Hybrid', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (51, 'Budget', 'Chevrolet', 'Suburban 1500', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (52, 'Luxury', 'Buick', 'Lucerne', 'Automatic', 'Gas', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (53, 'Luxury', 'Ford', 'Ranger', 'Automatic', 'Diesel', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (54, 'Luxury', 'Mazda', 'B-Series', 'Automatic', 'Electric', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (55, 'Luxury', 'Mercury', 'Lynx', 'Manual', 'Gas', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (56, 'Premium', 'Pontiac', 'Gemini', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (57, 'Luxury', 'Isuzu', 'i-350', 'Automatic', 'Hybrid', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (58, 'Budget', 'Chevrolet', '3500', 'Automatic', 'Hybrid', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (59, 'Luxury', 'Hyundai', 'Accent', 'Automatic', 'Hybrid', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (60, 'Luxury', 'Honda', 'Element', 'Manual', 'Gas', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (61, 'Standart', 'Mercury', 'Milan', 'Manual', 'Diesel', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (62, 'Luxury', 'Chevrolet', 'Corvette', 'Automatic', 'Gas', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (63, 'Luxury', 'Hyundai', 'Accent', 'Manual', 'Fuel-Oil', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (64, 'Premium', 'Dodge', 'Ram Wagon B150', 'Manual', 'Hybrid', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (65, 'Luxury', 'Buick', 'Century', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (66, 'Luxury', 'Dodge', 'Ram 2500 Club', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (67, 'Standart', 'Mercedes-Benz', 'S-Class', 'Automatic', 'Gas', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (68, 'Standart', 'Audi', 'TT', 'Manual', 'Diesel', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (69, 'Premium', 'Chevrolet', 'Beretta', 'Manual', 'Diesel', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (70, 'Standart', 'Lexus', 'IS-F', 'Automatic', 'Gas', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (71, 'Luxury', 'Nissan', '240SX', 'Automatic', 'Diesel', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (72, 'Budget', 'Isuzu', 'i-290', 'Automatic', 'Fuel-Oil', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (73, 'Budget', 'Hyundai', 'Elantra', 'Manual', 'Hybrid', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (74, 'Luxury', 'Honda', 'Civic', 'Manual', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (75, 'Premium', 'Jeep', 'Wrangler', 'Manual', 'Diesel', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (76, 'Luxury', 'Cadillac', 'CTS-V', 'Manual', 'Diesel', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (77, 'Luxury', 'Mazda', 'Millenia', 'Automatic', 'Diesel', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (78, 'Premium', 'Pontiac', 'Parisienne', 'Manual', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (79, 'Budget', 'Acura', 'NSX', 'Automatic', 'Gas', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (80, 'Premium', 'Volkswagen', 'Jetta', 'Automatic', 'Fuel-Oil', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (81, 'Premium', 'Mercedes-Benz', 'SL-Class', 'Automatic', 'Hybrid', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (82, 'Premium', 'Toyota', 'Camry Hybrid', 'Automatic', 'Diesel', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (83, 'Standart', 'Audi', 'A6', 'Manual', 'Gas', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (84, 'Premium', 'Porsche', '911', 'Manual', 'Gas', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (85, 'Premium', 'Mazda', 'RX-7', 'Automatic', 'Diesel', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (86, 'Standart', 'Dodge', 'Durango', 'Manual', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (87, 'Premium', 'Mitsubishi', 'Mirage', 'Automatic', 'Fuel-Oil', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (88, 'Luxury', 'Ford', 'Taurus', 'Automatic', 'Fuel-Oil', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (89, 'Luxury', 'Mercedes-Benz', 'E-Class', 'Automatic', 'Hybrid', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (90, 'Budget', 'Buick', 'Century', 'Automatic', 'Diesel', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (91, 'Luxury', 'Chevrolet', 'Prizm', 'Automatic', 'Hybrid', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (92, 'Standart', 'Isuzu', 'i-350', 'Manual', 'Diesel', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (93, 'Luxury', 'Buick', 'LeSabre', 'Automatic', 'Diesel', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (94, 'Standart', 'Mercedes-Benz', 'E-Class', 'Manual', 'Diesel', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (95, 'Luxury', 'Lexus', 'ES', 'Automatic', 'Hybrid', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (96, 'Premium', 'Dodge', 'Caravan', 'Automatic', 'Gas', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (97, 'Premium', 'Ferrari', '612 Scaglietti', 'Manual', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (98, 'Budget', 'BMW', 'X3', 'Automatic', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (99, 'Luxury', 'Nissan', 'Quest', 'Manual', 'Gas', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (100, 'Budget', 'Audi', 'A6', 'Manual', 'Fuel-Oil', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (101, 'Standart', 'GMC', 'Sierra', 'Automatic', 'Fuel-Oil', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (102, 'Premium', 'Dodge', 'Charger', 'Automatic', 'Gas', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (103, 'Premium', 'Mazda', 'MPV', 'Automatic', 'Diesel', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (104, 'Premium', 'Subaru', 'Outback', 'Automatic', 'Electric', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (105, 'Premium', 'Nissan', 'Maxima', 'Manual', 'Hybrid', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (106, 'Standart', 'Lexus', 'GS', 'Automatic', 'Gas', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (107, 'Luxury', 'BMW', '6 Series', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (108, 'Luxury', 'Buick', 'Lucerne', 'Automatic', 'Diesel', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (109, 'Standart', 'Dodge', 'Dakota', 'Manual', 'Diesel', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (110, 'Standart', 'Lincoln', 'Town Car', 'Automatic', 'Hybrid', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (111, 'Standart', 'Land Rover', 'Discovery', 'Automatic', 'Fuel-Oil', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (112, 'Premium', 'Mercedes-Benz', 'E-Class', 'Manual', 'Hybrid', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (113, 'Premium', 'Cadillac', 'CTS', 'Automatic', 'Hybrid', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (114, 'Premium', 'Mercedes-Benz', 'S-Class', 'Automatic', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (115, 'Premium', 'Hyundai', 'Excel', 'Manual', 'Diesel', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (116, 'Luxury', 'Chevrolet', 'Equinox', 'Manual', 'Gas', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (117, 'Luxury', 'Chevrolet', '1500', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (118, 'Luxury', 'Lotus', 'Exige', 'Manual', 'Hybrid', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (119, 'Premium', 'Suzuki', 'Swift', 'Automatic', 'Hybrid', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (120, 'Premium', 'Cadillac', 'DeVille', 'Automatic', 'Hybrid', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (121, 'Budget', 'Volkswagen', 'Touareg', 'Automatic', 'Fuel-Oil', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (122, 'Budget', 'Oldsmobile', 'Achieva', 'Manual', 'Gas', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (123, 'Standart', 'Audi', '100', 'Manual', 'Fuel-Oil', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (124, 'Standart', 'Pontiac', 'Gemini', 'Manual', 'Hybrid', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (125, 'Standart', 'Scion', 'xB', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (126, 'Budget', 'Kia', 'Optima', 'Automatic', 'Gas', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (127, 'Budget', 'Ford', 'Expedition', 'Manual', 'Fuel-Oil', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (128, 'Premium', 'Buick', 'Century', 'Automatic', 'Diesel', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (129, 'Premium', 'Chrysler', 'Voyager', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (130, 'Premium', 'Chevrolet', 'Express 2500', 'Automatic', 'Fuel-Oil', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (131, 'Luxury', 'Bentley', 'Azure', 'Manual', 'Electric', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (132, 'Luxury', 'Hyundai', 'Entourage', 'Manual', 'Hybrid', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (133, 'Premium', 'Mercedes-Benz', 'E-Class', 'Automatic', 'Diesel', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (134, 'Standart', 'Dodge', 'Intrepid', 'Manual', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (135, 'Standart', 'Mitsubishi', 'Galant', 'Automatic', 'Fuel-Oil', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (136, 'Standart', 'Kia', 'Sportage', 'Manual', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (137, 'Premium', 'Toyota', 'Avalon', 'Automatic', 'Fuel-Oil', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (138, 'Budget', 'Chevrolet', 'Avalanche 1500', 'Manual', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (139, 'Luxury', 'Chevrolet', 'Impala', 'Automatic', 'Hybrid', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (140, 'Budget', 'Volkswagen', 'Passat', 'Automatic', 'Hybrid', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (141, 'Premium', 'Dodge', 'Stealth', 'Manual', 'Fuel-Oil', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (142, 'Luxury', 'GMC', 'Jimmy', 'Manual', 'Fuel-Oil', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (143, 'Budget', 'Mercury', 'Mountaineer', 'Automatic', 'Gas', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (144, 'Standart', 'Lincoln', 'Navigator L', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (145, 'Luxury', 'Suzuki', 'XL-7', 'Automatic', 'Gas', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (146, 'Budget', 'Subaru', 'Forester', 'Manual', 'Gas', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (147, 'Budget', 'Saturn', 'L-Series', 'Manual', 'Gas', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (148, 'Premium', 'Scion', 'xB', 'Automatic', 'Hybrid', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (149, 'Premium', 'Chrysler', 'Town & Country', 'Manual', 'Diesel', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (150, 'Standart', 'Oldsmobile', 'Cutlass', 'Manual', 'Hybrid', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (151, 'Premium', 'Nissan', 'Cube', 'Manual', 'Hybrid', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (152, 'Standart', 'GMC', 'Savana 2500', 'Automatic', 'Gas', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (153, 'Premium', 'Volvo', 'V70', 'Manual', 'Diesel', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (154, 'Luxury', 'Mercedes-Benz', 'C-Class', 'Automatic', 'Hybrid', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (155, 'Standart', 'Mitsubishi', 'Eclipse', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (156, 'Standart', 'BMW', 'Z8', 'Automatic', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (157, 'Budget', 'Infiniti', 'Q', 'Manual', 'Gas', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (158, 'Standart', 'Pontiac', 'GTO', 'Manual', 'Hybrid', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (159, 'Premium', 'Oldsmobile', 'Aurora', 'Manual', 'Fuel-Oil', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (160, 'Luxury', 'Pontiac', 'Daewoo Kalos', 'Manual', 'Gas', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (161, 'Budget', 'GMC', 'Suburban 2500', 'Manual', 'Gas', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (162, 'Standart', 'Porsche', 'Boxster', 'Manual', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (163, 'Standart', 'Dodge', 'Neon', 'Manual', 'Hybrid', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (164, 'Premium', 'Chevrolet', 'Corvette', 'Manual', 'Gas', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (165, 'Luxury', 'Buick', 'LeSabre', 'Manual', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (166, 'Budget', 'Infiniti', 'G25', 'Manual', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (167, 'Premium', 'Chevrolet', 'Aveo', 'Automatic', 'Diesel', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (168, 'Budget', 'Mazda', 'B-Series Plus', 'Manual', 'Fuel-Oil', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (169, 'Budget', 'Honda', 'Odyssey', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (170, 'Standart', 'Subaru', 'Justy', 'Manual', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (171, 'Premium', 'Pontiac', 'Aztek', 'Automatic', 'Electric', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (172, 'Luxury', 'Ford', 'Focus', 'Manual', 'Diesel', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (173, 'Standart', 'Saab', '9-3', 'Manual', 'Hybrid', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (174, 'Budget', 'Volkswagen', 'Touareg', 'Manual', 'Gas', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (175, 'Luxury', 'Lexus', 'IS-F', 'Automatic', 'Hybrid', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (176, 'Premium', 'Kia', 'Carens', 'Automatic', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (177, 'Standart', 'Ford', 'F450', 'Automatic', 'Gas', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (178, 'Luxury', 'Pontiac', 'GTO', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (179, 'Luxury', 'Chrysler', 'Aspen', 'Manual', 'Electric', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (180, 'Standart', 'BMW', '5 Series', 'Automatic', 'Gas', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (181, 'Standart', 'GMC', '3500 Club Coupe', 'Automatic', 'Gas', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (182, 'Luxury', 'Ford', 'Explorer', 'Manual', 'Gas', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (183, 'Luxury', 'Lincoln', 'MKS', 'Manual', 'Electric', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (184, 'Budget', 'Ford', 'Econoline E150', 'Automatic', 'Diesel', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (185, 'Premium', 'Ford', 'F-Series', 'Automatic', 'Diesel', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (186, 'Budget', 'Mazda', 'RX-7', 'Automatic', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (187, 'Premium', 'Toyota', '4Runner', 'Manual', 'Hybrid', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (188, 'Standart', 'Isuzu', 'VehiCROSS', 'Manual', 'Electric', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (189, 'Premium', 'Dodge', 'Ram 2500', 'Automatic', 'Fuel-Oil', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (190, 'Standart', 'Nissan', 'Leaf', 'Automatic', 'Hybrid', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (191, 'Standart', 'Ford', 'Mustang', 'Automatic', 'Hybrid', 'Coupe');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (192, 'Premium', 'Isuzu', 'i-370', 'Manual', 'Hybrid', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (193, 'Budget', 'Lexus', 'GS', 'Automatic', 'Diesel', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (194, 'Standart', 'Chevrolet', '1500', 'Automatic', 'Diesel', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (195, 'Standart', 'Audi', 'A6', 'Automatic', 'Fuel-Oil', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (196, 'Premium', 'Acura', 'MDX', 'Automatic', 'Electric', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (197, 'Standart', 'Pontiac', 'Parisienne', 'Automatic', 'Diesel', 'Hatchback');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (198, 'Luxury', 'Ford', 'E350', 'Automatic', 'Hybrid', 'Sedan');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (199, 'Luxury', 'Volkswagen', 'rio', 'Manual', 'Diesel', 'SUV');
insert into Vehicles (id, class, make, model, transmission, engineType, bodyType) values (200, 'Luxury', 'GMC', '1500 Club Coupe', 'Manual', 'Electric', 'SUV');
